[package]
name = "downtube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustube = "0.6.0"
url = "2.5.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
